name: Build and Publish Docker Images

on:
  release:
    types: [published]

  push:
    branches:
      - develop
    paths-ignore:
      - ".gitmodules"
      - ".github/**"
      - "!.github/workflows/docker.yml" # Still run on changes to this file
      - ".gitignore"
      - "**.md"
      - "LICENSE"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push :tag
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-pia:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-pia:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Build and push :develop
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-pia:develop
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
